name: Github Build LedFx

on:
  push:
    branches:
      - patch-1

  workflow_dispatch:
    inputs:
      use-emoji:
        type: boolean
        description: Include  emojis
      win-portable:
        type: boolean
        description: 'Build Binary: win-portable'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -x {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11']
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install

      - name: Get Backend Version
        id: getbackendver
        run: |       
          echo "action_state=$(python3 ledfx/consts.py)" >> $GITHUB_ENV
          BINARY_NAME=LedFx-${{ runner.os }}
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV